# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'shop.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(952, 839)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/images/main_logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_44 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_44.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_44.setSpacing(0)
        self.verticalLayout_44.setObjectName("verticalLayout_44")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.frame_2)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setSpacing(0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.frame_4 = QtWidgets.QFrame(self.frame_2)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_4)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self.frame_4)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setStyleSheet("color: rgb(0, 85, 127);")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.verticalLayout_6.addWidget(self.frame_4)
        self.frame_5 = QtWidgets.QFrame(self.frame_2)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tableWidget = QtWidgets.QTableWidget(self.frame_5)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.verticalLayout_5.addWidget(self.tableWidget)
        self.verticalLayout_6.addWidget(self.frame_5)
        self.frame_6 = QtWidgets.QFrame(self.frame_2)
        self.frame_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_6.setObjectName("frame_6")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.frame_6)
        self.verticalLayout_32.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_32.setSpacing(5)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.search_text_frame = QtWidgets.QFrame(self.frame_6)
        self.search_text_frame.setMinimumSize(QtCore.QSize(0, 50))
        self.search_text_frame.setMaximumSize(QtCore.QSize(16777215, 50))
        self.search_text_frame.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.search_text_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_text_frame.setObjectName("search_text_frame")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.search_text_frame)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.search_text_frame)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.txt_search_name = QtWidgets.QLineEdit(self.search_text_frame)
        self.txt_search_name.setMinimumSize(QtCore.QSize(0, 25))
        self.txt_search_name.setMaximumSize(QtCore.QSize(16777215, 13213132))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_search_name.setFont(font)
        self.txt_search_name.setObjectName("txt_search_name")
        self.verticalLayout_2.addWidget(self.txt_search_name)
        self.verticalLayout_32.addWidget(self.search_text_frame)
        self.search_text_frame_2 = QtWidgets.QFrame(self.frame_6)
        self.search_text_frame_2.setMinimumSize(QtCore.QSize(0, 50))
        self.search_text_frame_2.setMaximumSize(QtCore.QSize(16777215, 50))
        self.search_text_frame_2.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.search_text_frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_text_frame_2.setObjectName("search_text_frame_2")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.search_text_frame_2)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.search_text_frame_2)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_3.addWidget(self.label_3)
        self.cmb_search_area = QtWidgets.QComboBox(self.search_text_frame_2)
        self.cmb_search_area.setMinimumSize(QtCore.QSize(0, 25))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmb_search_area.setFont(font)
        self.cmb_search_area.setObjectName("cmb_search_area")
        self.verticalLayout_3.addWidget(self.cmb_search_area)
        self.verticalLayout_32.addWidget(self.search_text_frame_2)
        self.btn_search = QtWidgets.QPushButton(self.frame_6)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/images/loupe.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_search.setIcon(icon1)
        self.btn_search.setObjectName("btn_search")
        self.verticalLayout_32.addWidget(self.btn_search)
        self.search_button_frame = QtWidgets.QFrame(self.frame_6)
        self.search_button_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.search_button_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.search_button_frame.setObjectName("search_button_frame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.search_button_frame)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(5)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btn_delete = QtWidgets.QPushButton(self.search_button_frame)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/images/trash.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_delete.setIcon(icon2)
        self.btn_delete.setObjectName("btn_delete")
        self.horizontalLayout.addWidget(self.btn_delete)
        self.btn_update = QtWidgets.QPushButton(self.search_button_frame)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/images/refresh.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_update.setIcon(icon3)
        self.btn_update.setObjectName("btn_update")
        self.horizontalLayout.addWidget(self.btn_update)
        self.btn_new = QtWidgets.QPushButton(self.search_button_frame)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/images/add-button.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_new.setIcon(icon4)
        self.btn_new.setObjectName("btn_new")
        self.horizontalLayout.addWidget(self.btn_new)
        self.btn_back = QtWidgets.QPushButton(self.search_button_frame)
        icon5 = QtGui.QIcon()
        icon5.addPixmap(QtGui.QPixmap(":/images/left-arrow.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_back.setIcon(icon5)
        self.btn_back.setObjectName("btn_back")
        self.horizontalLayout.addWidget(self.btn_back)
        self.verticalLayout_32.addWidget(self.search_button_frame)
        self.verticalLayout_6.addWidget(self.frame_6)
        self.horizontalLayout_2.addWidget(self.frame_2)
        self.entry_frame = QtWidgets.QFrame(self.frame)
        self.entry_frame.setMinimumSize(QtCore.QSize(0, 0))
        self.entry_frame.setFrameShape(QtWidgets.QFrame.Box)
        self.entry_frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.entry_frame.setObjectName("entry_frame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.entry_frame)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.frame_3 = QtWidgets.QFrame(self.entry_frame)
        self.frame_3.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_8.setSpacing(0)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.frame_7 = QtWidgets.QFrame(self.frame_3)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_7.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_7.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_9.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_9.setSpacing(0)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.label_4 = QtWidgets.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_4.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_9.addWidget(self.label_4)
        self.verticalLayout_8.addWidget(self.frame_7)
        self.frame_8 = QtWidgets.QFrame(self.frame_3)
        self.frame_8.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_8.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_10.setSpacing(0)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.txt_name = QtWidgets.QLineEdit(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_name.setFont(font)
        self.txt_name.setObjectName("txt_name")
        self.verticalLayout_10.addWidget(self.txt_name)
        self.verticalLayout_8.addWidget(self.frame_8)
        self.verticalLayout_4.addWidget(self.frame_3)
        self.frame_11 = QtWidgets.QFrame(self.entry_frame)
        self.frame_11.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_11.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_11.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_11.setObjectName("frame_11")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.frame_11)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.frame_12 = QtWidgets.QFrame(self.frame_11)
        self.frame_12.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_12.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_12.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_12.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_12.setObjectName("frame_12")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.frame_12)
        self.verticalLayout_12.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.label_5 = QtWidgets.QLabel(self.frame_12)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_5.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.verticalLayout_12.addWidget(self.label_5)
        self.verticalLayout_11.addWidget(self.frame_12)
        self.frame_13 = QtWidgets.QFrame(self.frame_11)
        self.frame_13.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_13.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_13.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_13.setObjectName("frame_13")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.frame_13)
        self.verticalLayout_13.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_13.setSpacing(0)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        self.txt_commercial = QtWidgets.QLineEdit(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_commercial.setFont(font)
        self.txt_commercial.setObjectName("txt_commercial")
        self.verticalLayout_13.addWidget(self.txt_commercial)
        self.verticalLayout_11.addWidget(self.frame_13)
        self.verticalLayout_4.addWidget(self.frame_11)
        self.frame_14 = QtWidgets.QFrame(self.entry_frame)
        self.frame_14.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_14.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_14.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_14.setObjectName("frame_14")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.frame_14)
        self.verticalLayout_14.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_14.setSpacing(0)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.frame_15 = QtWidgets.QFrame(self.frame_14)
        self.frame_15.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_15.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_15.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_15.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_15.setObjectName("frame_15")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.frame_15)
        self.verticalLayout_15.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_15.setSpacing(0)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        self.label_6 = QtWidgets.QLabel(self.frame_15)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_6.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.verticalLayout_15.addWidget(self.label_6)
        self.verticalLayout_14.addWidget(self.frame_15)
        self.frame_16 = QtWidgets.QFrame(self.frame_14)
        self.frame_16.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_16.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_16.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_16.setObjectName("frame_16")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.frame_16)
        self.verticalLayout_16.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_16.setSpacing(0)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.cmb_area = QtWidgets.QComboBox(self.frame_16)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmb_area.setFont(font)
        self.cmb_area.setObjectName("cmb_area")
        self.verticalLayout_16.addWidget(self.cmb_area)
        self.verticalLayout_14.addWidget(self.frame_16)
        self.verticalLayout_4.addWidget(self.frame_14)
        self.frame_17 = QtWidgets.QFrame(self.entry_frame)
        self.frame_17.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_17.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_17.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_17.setObjectName("frame_17")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.frame_17)
        self.verticalLayout_17.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_17.setSpacing(0)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        self.frame_18 = QtWidgets.QFrame(self.frame_17)
        self.frame_18.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_18.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_18.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_18.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_18.setObjectName("frame_18")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.frame_18)
        self.verticalLayout_18.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_18.setSpacing(0)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.label_7 = QtWidgets.QLabel(self.frame_18)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_7.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.verticalLayout_18.addWidget(self.label_7)
        self.verticalLayout_17.addWidget(self.frame_18)
        self.frame_19 = QtWidgets.QFrame(self.frame_17)
        self.frame_19.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.frame_19.setFont(font)
        self.frame_19.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_19.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_19.setObjectName("frame_19")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.frame_19)
        self.verticalLayout_19.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_19.setSpacing(0)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        self.txt_phone = QtWidgets.QLineEdit(self.frame_19)
        self.txt_phone.setObjectName("txt_phone")
        self.verticalLayout_19.addWidget(self.txt_phone)
        self.verticalLayout_17.addWidget(self.frame_19)
        self.verticalLayout_4.addWidget(self.frame_17)
        self.frame_20 = QtWidgets.QFrame(self.entry_frame)
        self.frame_20.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_20.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_20.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_20.setObjectName("frame_20")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.frame_20)
        self.verticalLayout_20.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_20.setSpacing(0)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.frame_21 = QtWidgets.QFrame(self.frame_20)
        self.frame_21.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_21.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_21.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_21.setObjectName("frame_21")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.frame_21)
        self.verticalLayout_21.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_21.setSpacing(0)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        self.label_8 = QtWidgets.QLabel(self.frame_21)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_8.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.verticalLayout_21.addWidget(self.label_8)
        self.verticalLayout_20.addWidget(self.frame_21)
        self.frame_22 = QtWidgets.QFrame(self.frame_20)
        self.frame_22.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_22.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_22.setObjectName("frame_22")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.frame_22)
        self.verticalLayout_22.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_22.setSpacing(0)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.txt_mail = QtWidgets.QLineEdit(self.frame_22)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_mail.setFont(font)
        self.txt_mail.setObjectName("txt_mail")
        self.verticalLayout_22.addWidget(self.txt_mail)
        self.verticalLayout_20.addWidget(self.frame_22)
        self.verticalLayout_4.addWidget(self.frame_20)
        self.frame_26 = QtWidgets.QFrame(self.entry_frame)
        self.frame_26.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_26.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_26.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_26.setObjectName("frame_26")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.frame_26)
        self.verticalLayout_26.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_26.setSpacing(0)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.frame_27 = QtWidgets.QFrame(self.frame_26)
        self.frame_27.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_27.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_27.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_27.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_27.setObjectName("frame_27")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.frame_27)
        self.verticalLayout_27.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_27.setSpacing(0)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        self.label_10 = QtWidgets.QLabel(self.frame_27)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_10.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_27.addWidget(self.label_10)
        self.verticalLayout_26.addWidget(self.frame_27)
        self.frame_28 = QtWidgets.QFrame(self.frame_26)
        self.frame_28.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_28.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_28.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_28.setObjectName("frame_28")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.frame_28)
        self.verticalLayout_28.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_28.setSpacing(0)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.txt_landing = QtWidgets.QLineEdit(self.frame_28)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_landing.setFont(font)
        self.txt_landing.setObjectName("txt_landing")
        self.verticalLayout_28.addWidget(self.txt_landing)
        self.verticalLayout_26.addWidget(self.frame_28)
        self.verticalLayout_4.addWidget(self.frame_26)
        self.frame_32 = QtWidgets.QFrame(self.entry_frame)
        self.frame_32.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_32.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_32.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_32.setObjectName("frame_32")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.frame_32)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setSpacing(0)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.frame_35 = QtWidgets.QFrame(self.frame_32)
        self.frame_35.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_35.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_35.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_35.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_35.setObjectName("frame_35")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_35)
        self.verticalLayout_36.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_36.setSpacing(0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.label_13 = QtWidgets.QLabel(self.frame_35)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_13.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_36.addWidget(self.label_13)
        self.verticalLayout_35.addWidget(self.frame_35)
        self.frame_36 = QtWidgets.QFrame(self.frame_32)
        self.frame_36.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_36.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_36.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_36.setObjectName("frame_36")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.frame_36)
        self.verticalLayout_37.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_37.setSpacing(0)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.txt_vip_rep = QtWidgets.QLineEdit(self.frame_36)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_vip_rep.setFont(font)
        self.txt_vip_rep.setObjectName("txt_vip_rep")
        self.verticalLayout_37.addWidget(self.txt_vip_rep)
        self.verticalLayout_35.addWidget(self.frame_36)
        self.verticalLayout_4.addWidget(self.frame_32)
        self.frame_37 = QtWidgets.QFrame(self.entry_frame)
        self.frame_37.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_37.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_37.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_37.setObjectName("frame_37")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.frame_37)
        self.verticalLayout_38.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_38.setSpacing(0)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.frame_38 = QtWidgets.QFrame(self.frame_37)
        self.frame_38.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_38.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_38.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_38.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_38.setObjectName("frame_38")
        self.verticalLayout_39 = QtWidgets.QVBoxLayout(self.frame_38)
        self.verticalLayout_39.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_39.setSpacing(0)
        self.verticalLayout_39.setObjectName("verticalLayout_39")
        self.label_14 = QtWidgets.QLabel(self.frame_38)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_14.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.verticalLayout_39.addWidget(self.label_14)
        self.verticalLayout_38.addWidget(self.frame_38)
        self.frame_39 = QtWidgets.QFrame(self.frame_37)
        self.frame_39.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_39.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_39.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_39.setObjectName("frame_39")
        self.verticalLayout_40 = QtWidgets.QVBoxLayout(self.frame_39)
        self.verticalLayout_40.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_40.setSpacing(0)
        self.verticalLayout_40.setObjectName("verticalLayout_40")
        self.txt_vip_comp = QtWidgets.QLineEdit(self.frame_39)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.txt_vip_comp.setFont(font)
        self.txt_vip_comp.setObjectName("txt_vip_comp")
        self.verticalLayout_40.addWidget(self.txt_vip_comp)
        self.verticalLayout_38.addWidget(self.frame_39)
        self.verticalLayout_4.addWidget(self.frame_37)
        self.frame_29 = QtWidgets.QFrame(self.entry_frame)
        self.frame_29.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_29.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_29.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_29.setObjectName("frame_29")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_29)
        self.verticalLayout_29.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_29.setSpacing(0)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.frame_30 = QtWidgets.QFrame(self.frame_29)
        self.frame_30.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_30.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_30.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_30.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_30.setObjectName("frame_30")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_30)
        self.verticalLayout_30.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.label_11 = QtWidgets.QLabel(self.frame_30)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_11.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_30.addWidget(self.label_11)
        self.verticalLayout_29.addWidget(self.frame_30)
        self.frame_31 = QtWidgets.QFrame(self.frame_29)
        self.frame_31.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_31.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_31.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_31.setObjectName("frame_31")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.frame_31)
        self.verticalLayout_31.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_31.setSpacing(0)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.cmb_currency = QtWidgets.QComboBox(self.frame_31)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmb_currency.setFont(font)
        self.cmb_currency.setObjectName("cmb_currency")
        self.cmb_currency.addItem("")
        self.cmb_currency.setItemText(0, "")
        self.cmb_currency.addItem("")
        self.cmb_currency.addItem("")
        self.cmb_currency.addItem("")
        self.cmb_currency.addItem("")
        self.verticalLayout_31.addWidget(self.cmb_currency)
        self.verticalLayout_29.addWidget(self.frame_31)
        self.verticalLayout_4.addWidget(self.frame_29)
        self.frame_40 = QtWidgets.QFrame(self.entry_frame)
        self.frame_40.setMaximumSize(QtCore.QSize(16777215, 70))
        self.frame_40.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_40.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_40.setObjectName("frame_40")
        self.verticalLayout_41 = QtWidgets.QVBoxLayout(self.frame_40)
        self.verticalLayout_41.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_41.setSpacing(0)
        self.verticalLayout_41.setObjectName("verticalLayout_41")
        self.frame_41 = QtWidgets.QFrame(self.frame_40)
        self.frame_41.setMinimumSize(QtCore.QSize(0, 30))
        self.frame_41.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_41.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_41.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_41.setObjectName("frame_41")
        self.verticalLayout_42 = QtWidgets.QVBoxLayout(self.frame_41)
        self.verticalLayout_42.setContentsMargins(5, 0, 0, 0)
        self.verticalLayout_42.setSpacing(0)
        self.verticalLayout_42.setObjectName("verticalLayout_42")
        self.label_15 = QtWidgets.QLabel(self.frame_41)
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(0, 85, 127);")
        self.label_15.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_42.addWidget(self.label_15)
        self.verticalLayout_41.addWidget(self.frame_41)
        self.frame_42 = QtWidgets.QFrame(self.frame_40)
        self.frame_42.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_42.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_42.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_42.setObjectName("frame_42")
        self.verticalLayout_43 = QtWidgets.QVBoxLayout(self.frame_42)
        self.verticalLayout_43.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_43.setSpacing(0)
        self.verticalLayout_43.setObjectName("verticalLayout_43")
        self.cmb_guide_com_pay = QtWidgets.QComboBox(self.frame_42)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.cmb_guide_com_pay.setFont(font)
        self.cmb_guide_com_pay.setObjectName("cmb_guide_com_pay")
        self.cmb_guide_com_pay.addItem("")
        self.cmb_guide_com_pay.setItemText(0, "")
        self.cmb_guide_com_pay.addItem("")
        self.cmb_guide_com_pay.addItem("")
        self.verticalLayout_43.addWidget(self.cmb_guide_com_pay)
        self.verticalLayout_41.addWidget(self.frame_42)
        self.verticalLayout_4.addWidget(self.frame_40)
        self.frame_10 = QtWidgets.QFrame(self.entry_frame)
        self.frame_10.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_10.setObjectName("frame_10")
        self.verticalLayout_4.addWidget(self.frame_10)
        self.frame_9 = QtWidgets.QFrame(self.entry_frame)
        self.frame_9.setMaximumSize(QtCore.QSize(16777215, 30))
        self.frame_9.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btn_save = QtWidgets.QPushButton(self.frame_9)
        icon6 = QtGui.QIcon()
        icon6.addPixmap(QtGui.QPixmap(":/images/floppy-disk.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.btn_save.setIcon(icon6)
        self.btn_save.setObjectName("btn_save")
        self.horizontalLayout_4.addWidget(self.btn_save)
        self.verticalLayout_4.addWidget(self.frame_9)
        self.horizontalLayout_2.addWidget(self.entry_frame)
        self.verticalLayout_44.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "TRAVIS - DIAMOND"))
        self.label.setText(_translate("MainWindow", "MAĞAZALAR"))
        self.label_2.setText(_translate("MainWindow", "Mağaza Adı"))
        self.label_3.setText(_translate("MainWindow", "Bölge"))
        self.btn_search.setText(_translate("MainWindow", "Ara"))
        self.btn_delete.setText(_translate("MainWindow", "Sil"))
        self.btn_update.setText(_translate("MainWindow", "Güncelle"))
        self.btn_new.setText(_translate("MainWindow", "Yeni Ekle"))
        self.btn_back.setText(_translate("MainWindow", "Geri"))
        self.label_4.setText(_translate("MainWindow", "Mağaza Adı"))
        self.label_5.setText(_translate("MainWindow", "Ticari Ünvan"))
        self.label_6.setText(_translate("MainWindow", "Bölge"))
        self.label_7.setText(_translate("MainWindow", "Telefon"))
        self.label_8.setText(_translate("MainWindow", "E-Posta"))
        self.label_10.setText(_translate("MainWindow", "Ayak Bastı Tutarı"))
        self.label_13.setText(_translate("MainWindow", "Vip Komisyon (Rep)"))
        self.label_14.setText(_translate("MainWindow", "Vip Komisyon (Şirket)"))
        self.label_11.setText(_translate("MainWindow", "Para Birimi"))
        self.cmb_currency.setItemText(1, _translate("MainWindow", "EUR"))
        self.cmb_currency.setItemText(2, _translate("MainWindow", "GBP"))
        self.cmb_currency.setItemText(3, _translate("MainWindow", "USD"))
        self.cmb_currency.setItemText(4, _translate("MainWindow", "TRY"))
        self.label_15.setText(_translate("MainWindow", "Rehber Komisyon Ödeme Türü"))
        self.cmb_guide_com_pay.setItemText(1, _translate("MainWindow", "MAĞAZADA"))
        self.cmb_guide_com_pay.setItemText(2, _translate("MainWindow", "CARİ"))
        self.btn_save.setText(_translate("MainWindow", "Kaydet"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())

